/* Untyped file generated by genType. */

import * as Curry from 'bs-platform/lib/es6/curry.js';

import * as FissionBS from './Fission.bs';

export const ipfsURL = FissionBS.ipfsURL;

export const cidsURL = FissionBS.cidsURL;

export const url = function (Arg1, Arg2) {
  const result = Curry._2(FissionBS.url, Arg1, Arg2);
  return result
};

export const content = function (Arg1, Arg2) {
  const result = Curry._2(FissionBS.content, Arg1, Arg2);
  return result
};

export const list = function (Arg1, Arg2) {
  const result = Curry._2(FissionBS.list, Arg1, [Arg2.username, Arg2.password]);
  return result
};

export const add = function (Arg1, Arg2, Arg3) {
  const result = Curry._3(FissionBS.add, Arg1, [Arg2.username, Arg2.password], Arg3);
  return result
};

export const addStr = function (Arg1, Arg2, Arg3) {
  const result = Curry._3(FissionBS.addStr, Arg1, [Arg2.username, Arg2.password], Arg3);
  return result
};

export const pin = function (Arg1, Arg2, Arg3) {
  const result = Curry._3(FissionBS.pin, Arg1, [Arg2.username, Arg2.password], Arg3);
  return result
};

export const remove = function (Arg1, Arg2, Arg3) {
  const result = Curry._3(FissionBS.remove, Arg1, [Arg2.username, Arg2.password], Arg3);
  return result
};

export const Simple_create = function (Arg1) {
  const result = FissionBS.Simple[0](Arg1);
  return {base:result[0], url:result[1], content:result[2]}
};

export const newSimple = function (Arg1) {
  const result = FissionBS.newSimple(Arg1);
  return {base:result[0], url:result[1], content:result[2]}
};

export const newUser = function (Arg1, Arg2) {
  const result = Curry._2(FissionBS.newUser, Arg1, [Arg2.username, Arg2.password]);
  return {base:result[0], url:result[1], content:result[2], add:result[3], addStr:result[4], pin:result[5], remove:result[6]}
};
