/* Untyped file generated by genType. */

import * as Curry from 'bs-platform/lib/es6/curry.js';

import * as FissionBS from './Fission.bs';

export const ipfsURL = FissionBS.ipfsURL;

export const cidsURL = FissionBS.cidsURL;

export const url = function (Arg1, Arg2) {
  const result = Curry._2(FissionBS.url, Arg1, Arg2);
  return result
};

export const content = function (Arg1, Arg2) {
  const result = Curry._2(FissionBS.content, Arg1, Arg2);
  return result
};

export const cids = function (Arg1, Arg2, Arg3) {
  const result = Curry._3(FissionBS.cids, Arg1, [Arg2.username, Arg2.password], Arg3);
  return result
};

export const add = function (Arg1, Arg2, Arg3) {
  const result = Curry._3(FissionBS.add, Arg1, [Arg2.username, Arg2.password], Arg3);
  return result
};

export const addString = function (Arg1, Arg2, Arg3) {
  const result = Curry._3(FissionBS.addString, Arg1, [Arg2.username, Arg2.password], Arg3);
  return result
};

export const addStream = function (Arg1, Arg2, Arg3) {
  const result = Curry._3(FissionBS.addStream, Arg1, [Arg2.username, Arg2.password], Arg3);
  return result
};

export const pin = function (Arg1, Arg2, Arg3) {
  const result = Curry._3(FissionBS.pin, Arg1, [Arg2.username, Arg2.password], Arg3);
  return result
};

export const remove = function (Arg1, Arg2, Arg3) {
  const result = Curry._3(FissionBS.remove, Arg1, [Arg2.username, Arg2.password], Arg3);
  return result
};

export const Simple_create = function (Arg1) {
  const result = FissionBS.Simple[0](Arg1);
  return {base:result[0], url:result[1], content:result[2]}
};

export const newSimple = function (Arg1) {
  const result = FissionBS.newSimple(Arg1);
  return {base:result[0], url:result[1], content:result[2]}
};

export const newUser = function (Arg1, Arg2) {
  const result = Curry._2(FissionBS.newUser, Arg1, [Arg2.username, Arg2.password]);
  return {base:result[0], url:result[1], content:result[2], cids:result[3], add:result[4], addString:result[5], addStream:result[6], pin:result[7], remove:result[8]}
};
