// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Axios = require("bs-axios/src/axios.js");
var Axios$1 = require("axios");

var baseURL = "http://localhost:1337";

var octetHeader = Axios.$$Headers[/* fromObj */0]({
      "content-type": "application/octet-stream"
    });

function convAuth(auth) {
  return {
          username: auth[/* username */0],
          password: auth[/* password */1]
        };
}

function url(baseURL, cid) {
  return baseURL + ("/ipfs/" + cid);
}

function content(cid) {
  return Axios$1.get(url(baseURL, cid)).then((function (response) {
                  return Promise.resolve(response.data);
                })).catch((function (error) {
                return Promise.resolve(error);
              }));
}

function list(auth) {
  return Axios$1.get("http://localhost:1337/ipfs/cids", {
                  auth: convAuth(auth)
                }).then((function (response) {
                  return Promise.resolve(response.data);
                })).catch((function (error) {
                return Promise.resolve(error);
              }));
}

function add(auth, content) {
  return Axios$1.post("http://localhost:1337/ipfs/", content, {
                  headers: octetHeader,
                  auth: convAuth(auth)
                }).then((function (response) {
                  return Promise.resolve(response.data);
                })).catch((function (error) {
                return Promise.resolve(error);
              }));
}

function addStr(auth, _str) {
  return Axios$1.post("http://localhost:1337/ipfs/", str, {
                  headers: octetHeader,
                  auth: convAuth(auth)
                }).then((function (response) {
                  return Promise.resolve(response.data);
                })).catch((function (error) {
                return Promise.resolve(error);
              }));
}

function pin(auth, cid) {
  return Axios$1.put(url(baseURL, cid), ({}), {
                  auth: convAuth(auth)
                }).then((function (response) {
                  return Promise.resolve(response.data);
                })).catch((function (error) {
                return Promise.resolve(error);
              }));
}

function remove(auth, cid) {
  return Axios$1.delete(url(baseURL, cid), {
                  auth: convAuth(auth)
                }).then((function (response) {
                  return Promise.resolve(response.data);
                })).catch((function (error) {
                return Promise.resolve(error);
              }));
}

function fissionUser(base, username, password) {
  var user = /* record */[
    /* username */username,
    /* password */password
  ];
  return /* record */[
          /* base */base,
          /* content */content,
          /* url */(function (param) {
              return url(base, param);
            }),
          /* add */(function (param) {
              return add(user, param);
            }),
          /* addStr */(function (param) {
              return addStr(user, param);
            }),
          /* pin */(function (param) {
              return pin(user, param);
            }),
          /* remove */(function (param) {
              return remove(user, param);
            })
        ];
}

function fission(base) {
  return /* record */[
          /* base */base,
          /* content */content,
          /* url */(function (param) {
              return url(base, param);
            }),
          /* login */(function (param, param$1) {
              return fissionUser(base, param, param$1);
            })
        ];
}

var env_username = "ca2c70bc13298c5109ee";

var env_password = "VlBgonAFjZon2wd2VkTR3uc*p-XMd(L_Zf$nFvACpHQShqJ_Hp2Pa";

exports.baseURL = baseURL;
exports.env_username = env_username;
exports.env_password = env_password;
exports.octetHeader = octetHeader;
exports.convAuth = convAuth;
exports.url = url;
exports.content = content;
exports.list = list;
exports.add = add;
exports.addStr = addStr;
exports.pin = pin;
exports.remove = remove;
exports.fissionUser = fissionUser;
exports.fission = fission;
/* octetHeader Not a pure module */
