// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Axios = require("axios");

var testCIDs = /* array */[
  "QmYFkqxQM63pcM5RzAQ4Fs9gei8YgHWu6DPWutfUs8Dvze",
  "QmYp9d8BC2HhDCUVH7JEUZAd6Hbxrc5wBRfUs8TqazJJP9",
  "QmYwXpFw1QGAWxEnQWFwLuVpdbupaBcEz2DTTRRRsCt9WR"
];

function get(prim) {
  return Axios.get(prim);
}

function getc(prim, prim$1) {
  return Axios.get(prim, prim$1);
}

function postDatac(prim, prim$1, prim$2) {
  return Axios.post(prim, prim$1, prim$2);
}

function putDatac(prim, prim$1, prim$2) {
  return Axios.put(prim, prim$1, prim$2);
}

function deletec(prim, prim$1) {
  return Axios.delete(prim, prim$1);
}

var AxiosMock = /* module */[
  /* get */get,
  /* getc */getc,
  /* postDatac */postDatac,
  /* putDatac */putDatac,
  /* deletec */deletec
];

var baseURL = "https://hostless.dev";

var username = "test_username";

var password = "test_password";

var strContent = "string content";

var testCID = "QmYFkqxQM63pcM5RzAQ4Fs9gei8YgHWu6DPWutfUs8Dvze";

exports.baseURL = baseURL;
exports.username = username;
exports.password = password;
exports.strContent = strContent;
exports.testCID = testCID;
exports.testCIDs = testCIDs;
exports.AxiosMock = AxiosMock;
/* axios Not a pure module */
