// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Fission$ReasonmlClient = require("../src/Fission.bs.js");

function randomString(param) {
  return "10osidfjpaeoi4j";
}

Jest.describe("Fission.Simple", (function (param) {
        var cid = /* record */[/* contents */""];
        Jest.beforeAllPromise(undefined, (function (param) {
                return Fission$ReasonmlClient.addStr(process.env.INTERPLANETARY_FISSION_URL, /* record */[
                              /* username */process.env.INTERPLANETARY_FISSION_USERNAME,
                              /* password */process.env.INTERPLANETARY_FISSION_PASSWORD
                            ], "10osidfjpaeoi4j").then((function (value) {
                              console.log("IN PROMISE: " + value);
                              cid[0] = value;
                              return Promise.resolve(value);
                            }));
              }));
        return Jest.test("filler", (function (param) {
                      console.log("HERE: " + cid[0]);
                      return Jest.Expect[/* toEqual */12]("1234", Jest.Expect[/* expect */0]("1234"));
                    }));
      }));

exports.randomString = randomString;
/*  Not a pure module */
